-- 当前生产/开发库原列均为 DATETIME NULL，保留现有可空性、默认值和自动更新时间。
-- 执行前：SHOW COLUMNS FROM article;
ALTER TABLE article
CHANGE COLUMN createTime create_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
CHANGE COLUMN updateTime update_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;

-- 执行后：SHOW COLUMNS FROM article;
